import { 
  ShopSettings, User, Item, IMEIRecord, Party, SaleInvoice, 
  PurchaseInvoice, InstallmentContract, Expense, AuditLog, WhatsAppMessage,
  RepairJob, Technician, RepairPayment, RepairSettings
} from '../types';

export const initialSettings: ShopSettings = {
  businessName: 'Apex Mobile City & Electronics',
  tagline: 'Wholesale, Retail & Easy Installments',
  address: 'Shop # 14-B, Ground Floor, Hafeez Centre, Main Boulevard, Gulberg III',
  city: 'Lahore, Pakistan',
  phone: '+92 42 35712345',
  whatsappPhone: '+92 300 1234567',
  email: 'contact@apexmobiles.pk',
  ntnStrn: 'NTN: 8492015-3 | STRN: 3277876123456',
  currency: 'PKR',
  currencySymbol: '₨',
  taxRate: 0,
  invoicePrefix: 'INV-2026-',
  nextInvoiceNum: 1045,
  poPrefix: 'PO-2026-',
  nextPoNum: 512,
  receiptPrefix: 'REC-2026-',
  nextReceiptNum: 820,
  installmentContractPrefix: 'INST-2026-',
  nextContractNum: 108,
  expensePrefix: 'EXP-2026-',
  nextExpenseNum: 340,
  inventoryValuationMethod: 'Average Cost',
  stockAlerts: {
    enableStockAlerts: true,
    defaultLowStockThreshold: 3, // Global low quantity threshold
    criticalStockThreshold: 1, // Critical alert threshold
    alertOnOutOfStock: true,
    notifyInDashboardBanner: true,
    notifyInHeaderBell: true,
    autoSuggestReorderQty: 5,
  },
  repairs: {
    ticketPrefix: 'REP-2026-',
    nextTicketNum: 1007,
    defaultWarranty: '30 Days',
    defaultLaborCharge: 1500,
    defaultEstimatedDays: 2,
    termsAndConditions: '1. Device inspection fee is non-refundable.\n2. No responsibility for customer data loss. Backups are customer responsibility.\n3. Physical impact or water damage void all repair warranties.\n4. Unclaimed devices past 30 days may be auctioned to recover parts and labor costs.\n5. Original physical receipt or digital verification required at collection.',
    commonComplaints: [
      'Broken Screen / Touch unresponsive',
      'Battery draining fast / Shutting down at 30%',
      'Not charging / Loose Type-C or Lightning port',
      'Water damage / Completely dead',
      'Speaker / Microphone distorted sound',
      'Rear Camera glass cracked / Blurry focus',
      'Stuck on boot logo / System crash',
      'Face ID / Fingerprint sensor failure',
      'No SIM / Weak network signal'
    ],
    commonDiagnoses: [
      'Original OLED Display cracked. Requires complete display assembly replacement.',
      'Battery capacity degraded. Requires high-capacity original battery replacement.',
      'Charging sub-board ribbon damaged. Requires genuine charging port flex replacement.',
      'PMIC / Power IC shorted due to liquid ingress. Ultrasonic board cleaning & reballing required.',
      'Ear speaker mesh clogged with carbon. Acoustic cleaning & test passed.',
      'Main rear camera sensor optical stabilization broken. Requires module replacement.'
    ],
    whatsappTemplates: {
      received: 'Dear {customer_name},\n\nYour {brand} {model} has been safely received for repair at {shop_name}.\n\nRepair Ticket: {repair_no}\nComplaint: {complaint}\nEst. Cost: Rs. {est_cost}\nEst. Delivery: {est_date}\n\nTrack your repair anytime using Ticket #{repair_no}. Thank you!\n{shop_name}',
      diagnosisCompleted: 'Dear {customer_name},\n\nTechnical diagnosis is complete for your {brand} {model} (Ticket #{repair_no}).\n\nDiagnosis: {diagnosis}\nTotal Estimate: Rs. {total}\n\nPlease reply with YES / APPROVED to start repair work.\n{shop_name}',
      waitingForParts: 'Dear {customer_name},\n\nYour repair job {repair_no} ({brand} {model}) is waiting for genuine replacement spare parts. We expect delivery shortly.\n{shop_name}',
      inProgress: 'Dear {customer_name},\n\nRepair work on your {brand} {model} (Ticket #{repair_no}) is now actively in progress on our workbench.\n{shop_name}',
      readyForCollection: 'Dear {customer_name},\n\nGreat news! Your {brand} {model} is fully repaired, tested, and READY FOR COLLECTION!\n\nTicket: {repair_no}\nTotal Amount: Rs. {total}\nPaid: Rs. {paid}\nRemaining Balance: Rs. {balance}\nWarranty: {warranty}\n\nKindly visit {shop_name} to collect your device.\nHafeez Centre, Lahore.',
      delivered: 'Dear {customer_name},\n\nThank you for collecting your device {brand} {model} (Ticket #{repair_no}).\n\nWarranty: {warranty} (Valid till {warranty_expiry}).\n\nThank you for choosing {shop_name}!'
    }
  },
  printer: {
    paperWidth: '80mm',
    fontSize: 'Medium',
    shopHeader: 'APEX MOBILE CITY & ELECTRONICS',
    shopSubHeader: 'Authorized Distributor & Installment Center\nHafeez Centre, Lahore | Tel: 0300-1234567',
    footerNotes: 'Thank you for your business!\nNo warranty on display/touch/water damage.\nGoods once sold cannot be returned without original receipt.',
    showLogo: true,
    showBarcode: true,
    autoCut: true,
    copies: 1,
    bottomFeedLines: 5,
  },
  whatsapp: {
    isConnected: true,
    phoneNumber: '+92 300 1234567',
    accountName: 'Apex Mobile City Official (Lahore)',
    status: 'Connected',
    provider: 'Direct / QR Gateway',
    templates: {
      saleInvoice: `Dear {customer_name},\n\nThank you for shopping with {shop_name}.\n\nInvoice: {invoice_no}\nDate: {date}\nItem: {items}\nTotal: {total}\nPaid: {paid}\nBalance: {balance}\n\nThank you! Visit again.`,
      installmentReminder: `Dear {customer_name},\n\nThis is a friendly reminder that your mobile installment of {installment_amount} for contract {contract_no} is due on {due_date}.\n\nRemaining Balance: {balance}\n\nKindly clear your due to avoid late penalties.\nThank you,\n{shop_name}\nPh: {shop_phone}`,
      installmentReceipt: `Payment Receipt\n\nDear {customer_name},\n\nWe have received payment of {paid} against Installment Contract {contract_no}.\nReceipt No: {receipt_no}\nDate: {date}\nRemaining Balance: {balance}\nNext Due Date: {next_due_date}\n\nThank you,\n{shop_name}`,
      paymentInReceipt: `Cash Receipt\n\nReceived {amount} from {customer_name}.\nReceipt: {receipt_no}\nDate: {date}\nCurrent Balance: {balance}\nPayment Method: {payment_method}\n\nThank you,\n{shop_name}`,
      outstandingBalance: `Account Statement\n\nDear {customer_name},\nYour current outstanding balance at {shop_name} is {balance}.\nKindly arrange payment at your earliest convenience.\nThank you.`
    }
  }
};

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Malik Tariq (Admin)',
    username: 'admin',
    email: 'admin@apexmobiles.pk',
    role: 'Admin',
    phone: '+92 300 1234567',
    active: true,
    pin: '1234',
    permissions: {
      viewSales: true,
      createSales: true,
      editSales: true,
      deleteSales: true,
      viewPurchases: true,
      createPurchases: true,
      viewInventory: true,
      manageInventory: true,
      viewInstallments: true,
      manageInstallments: true,
      viewParties: true,
      manageParties: true,
      viewExpenses: true,
      manageExpenses: true,
      viewReports: true,
      viewProfit: true,
      manageSettings: true,
      exportData: true,
      sendWhatsApp: true,
    },
    lastLogin: '2026-09-29 09:15 AM',
    createdAt: '2026-01-01',
  },
  {
    id: 'usr-2',
    name: 'Waqas Ahmed (Manager)',
    username: 'waqas',
    email: 'waqas@apexmobiles.pk',
    role: 'Manager',
    phone: '+92 321 9876543',
    active: true,
    pin: '5678',
    permissions: {
      viewSales: true,
      createSales: true,
      editSales: true,
      deleteSales: false,
      viewPurchases: true,
      createPurchases: true,
      viewInventory: true,
      manageInventory: true,
      viewInstallments: true,
      manageInstallments: true,
      viewParties: true,
      manageParties: true,
      viewExpenses: true,
      manageExpenses: true,
      viewReports: true,
      viewProfit: true,
      manageSettings: false,
      exportData: true,
      sendWhatsApp: true,
    },
    lastLogin: '2026-09-29 08:30 AM',
    createdAt: '2026-01-15',
  },
  {
    id: 'usr-3',
    name: 'Kashif Ali (Cashier)',
    username: 'cashier',
    email: 'cashier@apexmobiles.pk',
    role: 'Cashier',
    phone: '+92 333 4455667',
    active: true,
    pin: '1122',
    permissions: {
      viewSales: true,
      createSales: true,
      editSales: false,
      deleteSales: false,
      viewPurchases: false,
      createPurchases: false,
      viewInventory: true,
      manageInventory: false,
      viewInstallments: true,
      manageInstallments: true,
      viewParties: true,
      manageParties: false,
      viewExpenses: true,
      manageExpenses: true,
      viewReports: false,
      viewProfit: false,
      manageSettings: false,
      exportData: false,
      sendWhatsApp: true,
    },
    lastLogin: '2026-09-29 09:00 AM',
    createdAt: '2026-02-01',
  }
];

export const initialItems: Item[] = [
  {
    id: 'item-1',
    code: 'SAM-A15-BLU',
    barcode: '8806091234011',
    brand: 'Samsung',
    model: 'Galaxy A15',
    category: 'Smart Phones',
    subcategory: 'Mid-Range',
    color: 'Light Blue',
    ram: '6GB',
    storage: '128GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Airlink Official',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchasePrice: 45000,
    directPrice: 52000,
    installmentPrice: 62000,
    wholesalePrice: 49000,
    minStock: 3,
    currentStock: 6,
    reorderLevel: 2,
    unit: 'Pieces',
    description: 'Samsung Galaxy A15 6/128, Super AMOLED 90Hz, 50MP Triple Camera, 5000mAh Battery',
    active: true,
    createdAt: '2026-01-10',
    updatedAt: '2026-09-25',
  },
  {
    id: 'item-2',
    code: 'SAM-S24U-TGRY',
    barcode: '8806091234028',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    category: 'Smart Phones',
    subcategory: 'Flagship',
    color: 'Titanium Gray',
    ram: '12GB',
    storage: '512GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Samsung Pakistan',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchasePrice: 375000,
    directPrice: 410000,
    installmentPrice: 465000,
    wholesalePrice: 395000,
    minStock: 2,
    currentStock: 3,
    reorderLevel: 1,
    unit: 'Pieces',
    description: 'Galaxy AI, Snapdragon 8 Gen 3, Titanium frame, 200MP Quad Zoom, S-Pen included',
    active: true,
    createdAt: '2026-02-01',
    updatedAt: '2026-09-28',
  },
  {
    id: 'item-3',
    code: 'APL-15PM-NTIT',
    barcode: '1959490123456',
    brand: 'Apple',
    model: 'iPhone 15 Pro Max',
    category: 'Smart Phones',
    subcategory: 'Flagship',
    color: 'Natural Titanium',
    ram: '8GB',
    storage: '256GB',
    ptaStatus: 'PTA Approved',
    warranty: '1 Year Mercantile Pakistan',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchasePrice: 470000,
    directPrice: 515000,
    installmentPrice: 580000,
    wholesalePrice: 495000,
    minStock: 2,
    currentStock: 4,
    reorderLevel: 1,
    unit: 'Pieces',
    description: 'A17 Pro chip, Action button, USB-C 3.0, 5x Telephoto Optical zoom',
    active: true,
    createdAt: '2026-01-15',
    updatedAt: '2026-09-27',
  },
  {
    id: 'item-4',
    code: 'XIA-RN13-BLK',
    barcode: '6941812754321',
    brand: 'Xiaomi',
    model: 'Redmi Note 13',
    category: 'Smart Phones',
    subcategory: 'Budget',
    color: 'Midnight Black',
    ram: '8GB',
    storage: '256GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Smartlink Official',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchasePrice: 51000,
    directPrice: 58000,
    installmentPrice: 69000,
    wholesalePrice: 54500,
    minStock: 5,
    currentStock: 8,
    reorderLevel: 3,
    unit: 'Pieces',
    description: '108MP Ultra-clear camera, 120Hz FHD+ AMOLED display, 33W fast charging',
    active: true,
    createdAt: '2026-02-10',
    updatedAt: '2026-09-20',
  },
  {
    id: 'item-5',
    code: 'INF-N40P-TIT',
    barcode: '4895180765432',
    brand: 'Infinix',
    model: 'Note 40 Pro',
    category: 'Smart Phones',
    subcategory: 'Mid-Range',
    color: 'Titan Gold',
    ram: '12GB',
    storage: '256GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Carlcare Official',
    supplierId: 'pty-sup-3',
    supplierName: 'Royal Electronics Karachi',
    purchasePrice: 62000,
    directPrice: 71000,
    installmentPrice: 84000,
    wholesalePrice: 67000,
    minStock: 3,
    currentStock: 5,
    reorderLevel: 2,
    unit: 'Pieces',
    description: '70W All-Round FastCharge 2.0 + 20W Wireless MagCharge, 3D Curved 120Hz AMOLED',
    active: true,
    createdAt: '2026-03-01',
    updatedAt: '2026-09-24',
  },
  {
    id: 'item-6',
    code: 'TEC-SP20-GLD',
    barcode: '4895180798765',
    brand: 'Tecno',
    model: 'Spark 20',
    category: 'Smart Phones',
    subcategory: 'Budget',
    color: 'Gravity Black',
    ram: '8GB',
    storage: '256GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Carlcare',
    supplierId: 'pty-sup-3',
    supplierName: 'Royal Electronics Karachi',
    purchasePrice: 31000,
    directPrice: 36500,
    installmentPrice: 44000,
    wholesalePrice: 34000,
    minStock: 4,
    currentStock: 9,
    reorderLevel: 2,
    unit: 'Pieces',
    description: '50MP Ultra Clear camera, Dual Stereo Speakers with DTS, G85 Gaming Processor',
    active: true,
    createdAt: '2026-03-15',
    updatedAt: '2026-09-26',
  },
  {
    id: 'item-7',
    code: 'VIV-Y27-SEA',
    barcode: '6935117823412',
    brand: 'Vivo',
    model: 'Vivo Y27 4G',
    category: 'Smart Phones',
    subcategory: 'Budget',
    color: 'Sea Blue',
    ram: '6GB',
    storage: '128GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Vivo Official',
    supplierId: 'pty-sup-4',
    supplierName: 'Star Mobiles Lahore',
    purchasePrice: 38000,
    directPrice: 44000,
    installmentPrice: 52000,
    wholesalePrice: 41000,
    minStock: 3,
    currentStock: 6,
    reorderLevel: 2,
    unit: 'Pieces',
    description: '44W FlashCharge, 5000mAh Battery, 50MP Ultra HD Portrait Camera',
    active: true,
    createdAt: '2026-04-01',
    updatedAt: '2026-09-22',
  },
  {
    id: 'item-8',
    code: 'OPP-R11F-GRN',
    barcode: '6921815612345',
    brand: 'Oppo',
    model: 'Reno 11F 5G',
    category: 'Smart Phones',
    subcategory: 'Mid-Range',
    color: 'Palm Green',
    ram: '8GB',
    storage: '256GB',
    ptaStatus: 'Official Warranty',
    warranty: '1 Year Oppo Official',
    supplierId: 'pty-sup-4',
    supplierName: 'Star Mobiles Lahore',
    purchasePrice: 72000,
    directPrice: 82000,
    installmentPrice: 98000,
    wholesalePrice: 77000,
    minStock: 3,
    currentStock: 5,
    reorderLevel: 2,
    unit: 'Pieces',
    description: '64MP Ultra-Clear Triple Camera, 67W SUPERVOOC, Borderless 120Hz AMOLED',
    active: true,
    createdAt: '2026-04-10',
    updatedAt: '2026-09-25',
  },
  {
    id: 'item-9',
    code: 'ACC-AP2-WHT',
    barcode: '194253397166',
    brand: 'Apple',
    model: 'AirPods Pro 2nd Gen',
    category: 'Audio & Wearables',
    subcategory: 'Accessories',
    color: 'White',
    ptaStatus: 'N/A',
    warranty: '6 Months Local Replacement',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchasePrice: 6500,
    directPrice: 9500,
    installmentPrice: 12000,
    wholesalePrice: 8000,
    minStock: 5,
    currentStock: 14,
    reorderLevel: 3,
    unit: 'Pieces',
    description: 'Active Noise Cancellation, Adaptive Audio, USB-C MagSafe Charging Case',
    active: true,
    createdAt: '2026-05-01',
    updatedAt: '2026-09-28',
  },
  // REPAIR SPARE PARTS
  {
    id: 'part-1',
    code: 'PART-IP14P-OLED',
    barcode: '792019481021',
    brand: 'Apple',
    model: 'iPhone 14 Pro Max OLED Display Panel',
    category: 'Repair Spare Parts',
    subcategory: 'Screens',
    color: 'Black',
    ptaStatus: 'N/A',
    warranty: '3 Months Replacement',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchasePrice: 28000,
    directPrice: 38000,
    installmentPrice: 45000,
    wholesalePrice: 32000,
    minStock: 2,
    currentStock: 5,
    reorderLevel: 2,
    unit: 'Pieces',
    description: 'Original Super Retina XDR OLED Display Assembly with True Tone IC support',
    active: true,
    createdAt: '2026-06-01',
    updatedAt: '2026-09-20',
  },
  {
    id: 'part-2',
    code: 'PART-S23U-BAT',
    barcode: '792019481022',
    brand: 'Samsung',
    model: 'Galaxy S23 Original Battery 5000mAh',
    category: 'Repair Spare Parts',
    subcategory: 'Batteries',
    color: 'Standard',
    ptaStatus: 'N/A',
    warranty: '6 Months Replacement',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchasePrice: 4200,
    directPrice: 6500,
    installmentPrice: 8500,
    wholesalePrice: 5000,
    minStock: 3,
    currentStock: 8,
    reorderLevel: 3,
    unit: 'Pieces',
    description: '100% Genuine 5000mAh Li-Po replacement battery with NFC thermal sensor',
    active: true,
    createdAt: '2026-06-10',
    updatedAt: '2026-09-22',
  },
  {
    id: 'part-3',
    code: 'PART-USB-C-FLX',
    barcode: '792019481023',
    brand: 'Universal',
    model: 'Type-C Fast Charging Flex Sub-Board',
    category: 'Repair Spare Parts',
    subcategory: 'Charging Ports',
    color: 'Standard',
    ptaStatus: 'N/A',
    warranty: '1 Month Replacement',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchasePrice: 700,
    directPrice: 2200,
    installmentPrice: 3000,
    wholesalePrice: 1200,
    minStock: 5,
    currentStock: 18,
    reorderLevel: 5,
    unit: 'Pieces',
    description: 'Fast Charging 33W/67W support with original microphone & antenna contact points',
    active: true,
    createdAt: '2026-06-15',
    updatedAt: '2026-09-25',
  },
  {
    id: 'part-4',
    code: 'PART-IP13-CAM',
    barcode: '792019481024',
    brand: 'Apple',
    model: 'iPhone 13 Dual Camera Sensor Module',
    category: 'Repair Spare Parts',
    subcategory: 'Cameras',
    color: 'Black',
    ptaStatus: 'N/A',
    warranty: '3 Months Replacement',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchasePrice: 11000,
    directPrice: 16500,
    installmentPrice: 20000,
    wholesalePrice: 13500,
    minStock: 1,
    currentStock: 3,
    reorderLevel: 1,
    unit: 'Pieces',
    description: 'Original sensor-shift optical image stabilization camera assembly',
    active: true,
    createdAt: '2026-07-01',
    updatedAt: '2026-09-26',
  }
];

export const initialIMEIs: IMEIRecord[] = [
  // Samsung A15 units
  {
    id: 'imei-1',
    imei1: '861234050198231',
    imei2: '861234050198232',
    serialNumber: 'RF8N10A2B3C',
    itemId: 'item-1',
    brand: 'Samsung',
    model: 'Galaxy A15',
    color: 'Light Blue',
    storage: '128GB',
    ptaStatus: 'Official Warranty',
    purchaseInvoiceId: 'pur-1',
    purchaseInvoiceNo: 'PINV-2026-101',
    purchaseDate: '2026-09-10',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchaseCost: 45000,
    status: 'In Stock',
    history: [
      { date: '2026-09-10 11:30 AM', action: 'Purchased', note: 'Added to inventory from Pak Telecom', user: 'Malik Tariq' }
    ],
    createdAt: '2026-09-10',
    updatedAt: '2026-09-10',
  },
  {
    id: 'imei-2',
    imei1: '861234050198233',
    imei2: '861234050198234',
    serialNumber: 'RF8N10A2B3D',
    itemId: 'item-1',
    brand: 'Samsung',
    model: 'Galaxy A15',
    color: 'Light Blue',
    storage: '128GB',
    ptaStatus: 'Official Warranty',
    purchaseInvoiceId: 'pur-1',
    purchaseInvoiceNo: 'PINV-2026-101',
    purchaseDate: '2026-09-10',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchaseCost: 45000,
    status: 'In Stock',
    history: [
      { date: '2026-09-10 11:30 AM', action: 'Purchased', note: 'Added to inventory', user: 'Malik Tariq' }
    ],
    createdAt: '2026-09-10',
    updatedAt: '2026-09-10',
  },
  {
    id: 'imei-3',
    imei1: '861234050198235',
    imei2: '861234050198236',
    serialNumber: 'RF8N10A2B3E',
    itemId: 'item-1',
    brand: 'Samsung',
    model: 'Galaxy A15',
    color: 'Light Blue',
    storage: '128GB',
    ptaStatus: 'Official Warranty',
    purchaseInvoiceId: 'pur-1',
    purchaseInvoiceNo: 'PINV-2026-101',
    purchaseDate: '2026-09-10',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchaseCost: 45000,
    saleInvoiceId: 'inv-1001',
    saleInvoiceNo: 'INV-2026-1001',
    saleDate: '2026-09-18',
    customerId: 'pty-cus-1',
    customerName: 'Muhammad Rizwan',
    salePrice: 52000,
    saleType: 'Cash',
    status: 'Sold',
    history: [
      { date: '2026-09-10 11:30 AM', action: 'Purchased', note: 'Added to inventory', user: 'Malik Tariq' },
      { date: '2026-09-18 04:15 PM', action: 'Sold (Cash)', note: 'Sold to Muhammad Rizwan against INV-2026-1001', user: 'Kashif Ali' }
    ],
    createdAt: '2026-09-10',
    updatedAt: '2026-09-18',
  },
  {
    id: 'imei-4',
    imei1: '861234050198237',
    imei2: '861234050198238',
    serialNumber: 'RF8N10A2B3F',
    itemId: 'item-1',
    brand: 'Samsung',
    model: 'Galaxy A15',
    color: 'Light Blue',
    storage: '128GB',
    ptaStatus: 'Official Warranty',
    purchaseInvoiceId: 'pur-1',
    purchaseInvoiceNo: 'PINV-2026-101',
    purchaseDate: '2026-09-10',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchaseCost: 45000,
    customerId: 'pty-cus-2',
    customerName: 'Usman Ali',
    installmentContractId: 'inst-1',
    installmentContractNo: 'INST-2026-101',
    salePrice: 62000,
    saleType: 'Installment',
    status: 'Installment Active',
    history: [
      { date: '2026-09-10 11:30 AM', action: 'Purchased', note: 'Stock added', user: 'Malik Tariq' },
      { date: '2026-09-15 02:20 PM', action: 'Sold on Installment', note: 'Contract INST-2026-101 created for Usman Ali (6 months plan)', user: 'Waqas Ahmed' }
    ],
    createdAt: '2026-09-10',
    updatedAt: '2026-09-15',
  },
  // S24 Ultra
  {
    id: 'imei-5',
    imei1: '359871029384751',
    imei2: '359871029384752',
    serialNumber: 'SM928B339281',
    itemId: 'item-2',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    color: 'Titanium Gray',
    storage: '512GB',
    ptaStatus: 'Official Warranty',
    purchaseInvoiceId: 'pur-2',
    purchaseInvoiceNo: 'PINV-2026-102',
    purchaseDate: '2026-09-12',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    purchaseCost: 375000,
    status: 'In Stock',
    history: [
      { date: '2026-09-12 01:00 PM', action: 'Purchased', note: 'Flagship stock received', user: 'Malik Tariq' }
    ],
    createdAt: '2026-09-12',
    updatedAt: '2026-09-12',
  },
  // iPhone 15 Pro Max
  {
    id: 'imei-6',
    imei1: '357192837465012',
    imei2: '357192837465013',
    serialNumber: 'F2LQK09N1P23',
    itemId: 'item-3',
    brand: 'Apple',
    model: 'iPhone 15 Pro Max',
    color: 'Natural Titanium',
    storage: '256GB',
    ptaStatus: 'PTA Approved',
    purchaseInvoiceId: 'pur-3',
    purchaseInvoiceNo: 'PINV-2026-103',
    purchaseDate: '2026-09-15',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchaseCost: 470000,
    status: 'In Stock',
    history: [
      { date: '2026-09-15 03:45 PM', action: 'Purchased', note: 'PTA Approved stock verified', user: 'Malik Tariq' }
    ],
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
  },
  // Redmi Note 13
  {
    id: 'imei-7',
    imei1: '864920194827361',
    imei2: '864920194827362',
    serialNumber: 'XIA2026RN1301',
    itemId: 'item-4',
    brand: 'Xiaomi',
    model: 'Redmi Note 13',
    color: 'Midnight Black',
    storage: '256GB',
    ptaStatus: 'Official Warranty',
    purchaseInvoiceId: 'pur-4',
    purchaseInvoiceNo: 'PINV-2026-104',
    purchaseDate: '2026-09-14',
    supplierId: 'pty-sup-2',
    supplierName: 'Hafeez Centre Wholesale Hub',
    purchaseCost: 51000,
    status: 'In Stock',
    history: [
      { date: '2026-09-14 10:10 AM', action: 'Purchased', note: 'Stock added', user: 'Malik Tariq' }
    ],
    createdAt: '2026-09-14',
    updatedAt: '2026-09-14',
  }
];

export const initialParties: Party[] = [
  {
    id: 'pty-cus-1',
    type: 'Customer',
    name: 'Muhammad Rizwan',
    fatherName: 'Abdul Ghaffar',
    cnic: '35201-1234567-1',
    mobile: '0302-8492011',
    whatsapp: '+923028492011',
    address: 'House 42, St 5, Model Town C-Block',
    city: 'Lahore',
    email: 'rizwan.m@gmail.com',
    openingBalance: 0,
    currentBalance: 0,
    creditLimit: 50000,
    remarks: 'Regular Cash Buyer',
    totalSales: 52000,
    active: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'pty-cus-2',
    type: 'Installment Customer',
    name: 'Usman Ali',
    fatherName: 'Bashir Ahmed',
    cnic: '35202-9876543-3',
    mobile: '0321-4567890',
    whatsapp: '+923214567890',
    address: 'Flat 302, Green Complex, Garden Town',
    city: 'Lahore',
    email: 'usman.ali@yahoo.com',
    openingBalance: 0,
    currentBalance: 32000, // Remaining balance on contract
    creditLimit: 100000,
    remarks: 'Verified salary slip & tenant agreement on file',
    totalSales: 62000,
    active: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'pty-cus-3',
    type: 'Wholesale Customer',
    name: 'Hamza Sheikh (Al-Madina Mobiles)',
    fatherName: 'Sheikh Tariq',
    cnic: '35201-5544332-5',
    mobile: '0333-7788990',
    whatsapp: '+923337788990',
    address: 'Shop # 8, Panorama Centre, Mall Road',
    city: 'Lahore',
    email: 'almadina.mobiles@gmail.com',
    openingBalance: 45000,
    currentBalance: 95000,
    creditLimit: 500000,
    remarks: 'Wholesale client. Settles bill every 15 days.',
    totalSales: 280000,
    active: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'pty-cus-4',
    type: 'Installment Customer',
    name: 'Tariq Mehmood',
    fatherName: 'Muhammad Din',
    cnic: '35201-8472910-7',
    mobile: '0345-1122334',
    whatsapp: '+923451122334',
    address: 'G-14, Johar Town, Phase 1',
    city: 'Lahore',
    openingBalance: 0,
    currentBalance: 0,
    creditLimit: 75000,
    remarks: 'Completed previous installment on time',
    active: true,
    createdAt: '2026-04-12',
  },
  // Suppliers
  {
    id: 'pty-sup-1',
    type: 'Supplier',
    name: 'Pak Telecom Distributors',
    mobile: '0300-9988776',
    whatsapp: '+923009988776',
    address: 'Plaza 4, Hall Road',
    city: 'Lahore',
    email: 'orders@paktelecom.com.pk',
    openingBalance: 120000,
    currentBalance: 120000,
    remarks: 'Official Samsung & Xiaomi distributor in Lahore',
    totalPurchases: 1850000,
    active: true,
    createdAt: '2026-01-05',
  },
  {
    id: 'pty-sup-2',
    type: 'Supplier',
    name: 'Hafeez Centre Wholesale Hub',
    mobile: '0322-5566778',
    whatsapp: '+923225566778',
    address: 'LG 22, Hafeez Centre, Main Boulevard',
    city: 'Lahore',
    email: 'hafeezhub@gmail.com',
    openingBalance: 85000,
    currentBalance: 85000,
    remarks: 'Direct Apple importer and accessories wholesaler',
    totalPurchases: 1420000,
    active: true,
    createdAt: '2026-01-08',
  },
  {
    id: 'pty-sup-3',
    type: 'Supplier',
    name: 'Royal Electronics Karachi',
    mobile: '0331-2233445',
    whatsapp: '+923312233445',
    address: 'Saddar Star City Mall',
    city: 'Karachi',
    openingBalance: 0,
    currentBalance: 0,
    remarks: 'Infinix & Tecno regional vendor',
    totalPurchases: 620000,
    active: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'pty-sup-4',
    type: 'Supplier',
    name: 'Star Mobiles Lahore',
    mobile: '0301-4455667',
    whatsapp: '+923014455667',
    address: 'Hall Road Commercial Zone',
    city: 'Lahore',
    openingBalance: 0,
    currentBalance: 0,
    remarks: 'Vivo & Oppo vendor',
    totalPurchases: 450000,
    active: true,
    createdAt: '2026-03-01',
  }
];

export const initialInstallments: InstallmentContract[] = [
  {
    id: 'inst-1',
    contractNo: 'INST-2026-101',
    date: '2026-08-15',
    customerId: 'pty-cus-2',
    customerName: 'Usman Ali',
    customerFatherName: 'Bashir Ahmed',
    customerCnic: '35202-9876543-3',
    customerPhone: '0321-4567890',
    customerWhatsApp: '+923214567890',
    customerAddress: 'Flat 302, Green Complex, Garden Town, Lahore',

    guarantorName: 'Zahid Hussain',
    guarantorFatherName: 'Hussain Bakhsh',
    guarantorCnic: '35201-1122334-9',
    guarantorPhone: '0300-8899001',
    guarantorAddress: 'House 18, Block D, Garden Town, Lahore',
    guarantorRelation: 'Uncle / Govt Officer (Grade 17)',
    referencePerson: 'Mian Asif (Friend)',
    referencePhone: '0333-1234567',

    itemId: 'item-1',
    itemName: 'Samsung Galaxy A15',
    brand: 'Samsung',
    model: 'Galaxy A15',
    color: 'Light Blue',
    storage: '128GB',
    imeiId: 'imei-4',
    imei1: '861234050198237',
    imei2: '861234050198238',
    purchaseCost: 45000,

    directCashPrice: 52000,
    totalInstallmentPrice: 62000,
    downPayment: 14000,
    remainingBalance: 32000, // 62000 - 14000 = 48000. 48000 - 16000 paid = 32000 remaining.
    totalPaid: 30000, // 14000 down payment + 2 x 8000 installments
    numberOfInstallments: 6,
    installmentFrequency: 'Monthly',
    installmentAmount: 8000,
    firstDueDate: '2026-09-15',
    nextDueDate: '2026-10-15',
    durationMonths: 6,
    expectedProfit: 17000, // 62000 - 45000
    realizedProfit: 8225,

    status: 'Active',
    schedule: [
      {
        id: 'sch-1',
        installmentNo: 1,
        dueDate: '2026-09-15',
        amount: 8000,
        paidAmount: 8000,
        remainingAmount: 0,
        paidDate: '2026-09-14',
        status: 'Paid',
        receiptNo: 'REC-2026-805',
        notes: 'Paid via JazzCash'
      },
      {
        id: 'sch-2',
        installmentNo: 2,
        dueDate: '2026-10-15',
        amount: 8000,
        paidAmount: 8000,
        remainingAmount: 0,
        paidDate: '2026-09-28',
        status: 'Paid',
        receiptNo: 'REC-2026-819',
        notes: 'Paid early via Cash'
      },
      {
        id: 'sch-3',
        installmentNo: 3,
        dueDate: '2026-11-15',
        amount: 8000,
        paidAmount: 0,
        remainingAmount: 8000,
        status: 'Pending'
      },
      {
        id: 'sch-4',
        installmentNo: 4,
        dueDate: '2026-12-15',
        amount: 8000,
        paidAmount: 0,
        remainingAmount: 8000,
        status: 'Pending'
      },
      {
        id: 'sch-5',
        installmentNo: 5,
        dueDate: '2027-01-15',
        amount: 8000,
        paidAmount: 0,
        remainingAmount: 8000,
        status: 'Pending'
      },
      {
        id: 'sch-6',
        installmentNo: 6,
        dueDate: '2027-02-15',
        amount: 8000,
        paidAmount: 0,
        remainingAmount: 8000,
        status: 'Pending'
      }
    ],
    payments: [
      {
        id: 'pay-1',
        receiptNo: 'REC-2026-805',
        date: '2026-09-14',
        amount: 8000,
        paymentMethod: 'JazzCash',
        installmentNo: 1,
        collectedBy: 'Kashif Ali',
        notes: 'Trx ID: 0981248712'
      },
      {
        id: 'pay-2',
        receiptNo: 'REC-2026-819',
        date: '2026-09-28',
        amount: 8000,
        paymentMethod: 'Cash',
        installmentNo: 2,
        collectedBy: 'Waqas Ahmed',
        notes: 'Paid at counter'
      }
    ],
    terms: '1. The device remains the legal security asset of the shop until 100% installments are cleared.\n2. In case of 3 consecutive defaulted installments, the shop reserves legal right to confiscate device or file recovery via Guarantor.\n3. Defaulter fine: Rs. 500 per week after 7 days grace period.',
    notes: 'Good client, salaried professional.',
    createdAt: '2026-08-15',
  }
];

export const initialSales: SaleInvoice[] = [
  {
    id: 'inv-1001',
    invoiceNo: 'INV-2026-1001',
    date: '2026-09-18',
    time: '04:15 PM',
    customerId: 'pty-cus-1',
    customerName: 'Muhammad Rizwan',
    customerPhone: '0302-8492011',
    customerCnic: '35201-1234567-1',
    customerAddress: 'Model Town C-Block, Lahore',
    saleType: 'Cash',
    items: [
      {
        id: 'si-1',
        itemId: 'item-1',
        itemName: 'Samsung Galaxy A15',
        brand: 'Samsung',
        model: 'Galaxy A15',
        color: 'Light Blue',
        storage: '128GB',
        imei1: '861234050198235',
        imei2: '861234050198236',
        imeiId: 'imei-3',
        quantity: 1,
        purchaseCost: 45000,
        unitPrice: 52000,
        saleType: 'Cash',
        discount: 0,
        tax: 0,
        total: 52000,
        profit: 7000,
      }
    ],
    subtotal: 52000,
    discount: 0,
    tax: 0,
    grandTotal: 52000,
    paidAmount: 52000,
    remainingAmount: 0,
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    totalProfit: 7000,
    salesmanId: 'usr-3',
    salesmanName: 'Kashif Ali',
    notes: 'Cash sale with box pack warranty card',
    createdAt: '2026-09-18 16:15:00',
  }
];

export const initialPurchases: PurchaseInvoice[] = [
  {
    id: 'pur-1',
    invoiceNo: 'PINV-2026-101',
    date: '2026-09-10',
    time: '11:30 AM',
    supplierId: 'pty-sup-1',
    supplierName: 'Pak Telecom Distributors',
    supplierPhone: '0300-9988776',
    items: [
      {
        id: 'pi-1',
        itemId: 'item-1',
        itemName: 'Samsung Galaxy A15 6/128',
        brand: 'Samsung',
        model: 'Galaxy A15',
        color: 'Light Blue',
        storage: '128GB',
        imeis: [
          { imei1: '861234050198231', imei2: '861234050198232' },
          { imei1: '861234050198233', imei2: '861234050198234' },
          { imei1: '861234050198235', imei2: '861234050198236' },
          { imei1: '861234050198237', imei2: '861234050198238' }
        ],
        quantity: 4,
        purchasePrice: 45000,
        discount: 0,
        tax: 0,
        total: 180000,
      }
    ],
    subtotal: 180000,
    discount: 0,
    tax: 0,
    grandTotal: 180000,
    paidAmount: 180000,
    remainingAmount: 0,
    paymentMethod: 'Bank',
    paymentStatus: 'Paid',
    notes: 'Paid via Meezan Bank transfer',
    createdAt: '2026-09-10 11:30:00',
  }
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    expenseNo: 'EXP-2026-338',
    date: '2026-09-28',
    time: '02:00 PM',
    category: 'Electricity',
    amount: 14500,
    paymentMethod: 'Cash',
    description: 'LESCO Commercial Shop electricity bill September',
    paidTo: 'LESCO Sub-division Gulberg',
    referenceNo: 'LESCO-89123847',
    remarks: 'Paid on due date',
    createdAt: '2026-09-28 14:00:00',
  },
  {
    id: 'exp-2',
    expenseNo: 'EXP-2026-339',
    date: '2026-09-29',
    time: '11:15 AM',
    category: 'Tea/Food',
    amount: 850,
    paymentMethod: 'Cash',
    description: 'Daily shop tea, mineral water bottles, and guest refreshment',
    paidTo: 'Hafeez Centre Cafeteria',
    remarks: 'Counter expense',
    createdAt: '2026-09-29 11:15:00',
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-29 09:15:00',
    userId: 'usr-1',
    userName: 'Malik Tariq',
    action: 'LOGIN',
    module: 'Security',
    recordId: 'usr-1',
    details: 'Admin logged into POS console successfully',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-28 17:40:00',
    userId: 'usr-2',
    userName: 'Waqas Ahmed',
    action: 'INSTALLMENT_COLLECTION',
    module: 'Installments',
    recordId: 'inst-1',
    details: 'Collected installment #2 (₨ 8,000) from Usman Ali against contract INST-2026-101',
  }
];

export const initialWhatsAppMessages: WhatsAppMessage[] = [
  {
    id: 'wa-1',
    timestamp: '2026-09-28 17:42:00',
    recipientPhone: '+923214567890',
    recipientName: 'Usman Ali',
    type: 'Payment Receipt',
    body: 'Payment Receipt\n\nDear Usman Ali,\n\nWe have received payment of ₨ 8,000 against Installment Contract INST-2026-101.\nReceipt No: REC-2026-819\nDate: 2026-09-28\nRemaining Balance: ₨ 32,000\nNext Due Date: 2026-10-15\n\nThank you,\nApex Mobile City & Electronics',
    status: 'Read',
    referenceId: 'REC-2026-819',
  }
];

// REPAIR TECHNICIANS
export const initialTechnicians: Technician[] = [
  {
    id: 'tech-1',
    name: 'Ustad Ali Raza',
    phone: '+92 301 7654321',
    cnic: '35202-1234567-1',
    address: 'Hafeez Centre Lab 3, Gulberg III, Lahore',
    specializations: ['Apple Repair', 'Screen Replacement', 'IC Repair', 'Water Damage'],
    commissionRate: 30,
    salary: 45000,
    active: true,
    createdAt: '2026-01-10',
  },
  {
    id: 'tech-2',
    name: 'Bilal Hussain',
    phone: '+92 321 8899001',
    cnic: '35201-9876543-3',
    address: 'Ichhra, Ferozepur Road, Lahore',
    specializations: ['Hardware', 'Charging', 'Screen Replacement', 'Android Repair'],
    commissionRate: 25,
    salary: 35000,
    active: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'tech-3',
    name: 'Hamza Tariq',
    phone: '+92 345 1122334',
    cnic: '35202-5544332-5',
    address: 'Model Town Link Road, Lahore',
    specializations: ['Software', 'Network', 'Android Repair'],
    commissionRate: 20,
    salary: 30000,
    active: true,
    createdAt: '2026-03-01',
  }
];

// REPAIR JOBS / TICKETS
export const initialRepairs: RepairJob[] = [
  {
    id: 'rep-1',
    repairNo: 'REP-2026-1001',
    date: '2026-09-28',
    time: '11:30 AM',
    customerId: 'pty-cus-1',
    customerName: 'Muhammad Hamza',
    customerFatherName: 'Muhammad Arshad',
    customerPhone: '+92 300 9876543',
    customerWhatsApp: '+92 300 9876543',
    customerCnic: '35201-7654321-3',
    customerAddress: 'House 42, Street 7, Cavalry Ground, Lahore',
    deviceType: 'Smartphone',
    brand: 'Apple',
    model: 'iPhone 14 Pro Max',
    imei1: '354890119827361',
    imei2: '354890119827362',
    serialNumber: 'DN6QW10A3K9',
    color: 'Deep Purple',
    storage: '256GB',
    devicePassword: 'PIN: 7890',
    physicalCondition: 'Front screen badly shattered, edge dents near volume rocker, rear glass intact',
    checklist: {
      screen: 'Damaged',
      touch: 'Not Working',
      camera: 'Working',
      speaker: 'Working',
      microphone: 'Working',
      charging: 'Working',
      battery: 'Working',
      wifi: 'Working',
      bluetooth: 'Working',
      sim: 'Working',
      fingerprint: 'Not Tested',
      faceId: 'Working',
      buttons: 'Working',
      vibration: 'Working',
      flash: 'Working',
      network: 'Working',
      body: 'Damaged',
      waterDamage: 'Working',
      backGlass: 'Working',
      other: 'TrueTone IC needs to be transferred to new OLED panel',
    },
    accessories: {
      charger: false,
      cable: false,
      box: false,
      sim: true,
      memoryCard: false,
      earphones: false,
      backCover: true,
      other: 'Silicone case submitted',
    },
    photos: [
      {
        id: 'p-1',
        url: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400',
        caption: 'Cracked front OLED screen before disassembly',
        uploadedAt: '2026-09-28 11:35 AM',
      }
    ],
    customerComplaint: 'Dropped on marble floor, display went completely black with green lines and no touch response',
    problemDescription: 'Cracked front glass + inner OLED panel bleeding. Phone powers on and vibrates on mute switch',
    visibleDamage: 'Glass shattered on top right corner above dynamic island',
    technicianDiagnosis: 'Complete OLED display assembly fractured. Internal motherboard and Face ID sensors intact.',
    faultFound: 'Display digitizer & OLED ruptured',
    requiredRepair: 'Replace with genuine Super Retina XDR OLED Display & reprogram TrueTone EEPROM',
    technicianNotes: 'Carefully peel ambient light sensor flex to preserve Face ID pairing',
    priority: 'Urgent',
    status: 'Under Repair',
    statusHistory: [
      {
        id: 'sh-1',
        status: 'Received',
        date: '2026-09-28',
        time: '11:30 AM',
        user: 'Malik Tariq',
        remarks: 'Device received with broken display and silicone cover. Advance collected.',
      },
      {
        id: 'sh-2',
        status: 'Inspection',
        date: '2026-09-28',
        time: '12:15 PM',
        user: 'Ustad Ali Raza',
        technicianName: 'Ustad Ali Raza',
        remarks: 'Physical inspection completed. Internal board tested OK.',
      },
      {
        id: 'sh-3',
        status: 'Estimate Prepared',
        date: '2026-09-28',
        time: '01:00 PM',
        user: 'Ustad Ali Raza',
        remarks: 'Estimate prepared: Rs 40,500 total.',
      },
      {
        id: 'sh-4',
        status: 'Approved',
        date: '2026-09-28',
        time: '02:30 PM',
        user: 'Waqas Ahmed',
        remarks: 'Customer approved estimate over phone call.',
      },
      {
        id: 'sh-5',
        status: 'Under Repair',
        date: '2026-09-29',
        time: '10:00 AM',
        user: 'Ustad Ali Raza',
        technicianName: 'Ustad Ali Raza',
        remarks: 'Screen detached, transferring sensors and TrueTone IC.',
      }
    ],
    assignedTechnicianId: 'tech-1',
    assignedTechnicianName: 'Ustad Ali Raza',
    estimatedCompletionDate: '2026-09-29',
    partsUsed: [
      {
        id: 'rpu-1',
        partItemId: 'part-1',
        partName: 'iPhone 14 Pro Max OLED Display Panel',
        quantity: 1,
        costPrice: 28000,
        sellingPrice: 38000,
        totalSelling: 38000,
        addedAt: '2026-09-29 10:05 AM',
        addedBy: 'Ustad Ali Raza',
      }
    ],
    partsCost: 28000,
    partsSellingPrice: 38000,
    laborCharge: 2500,
    otherCharges: 0,
    discount: 500,
    totalCost: 30500,
    grandTotal: 40000,
    advancePayment: 10000,
    paidAmount: 10000,
    remainingAmount: 30000,
    paymentStatus: 'Partial',
    repairProfit: 9500,
    customerApproval: {
      status: 'Approved',
      date: '2026-09-28',
      time: '02:30 PM',
      approvedBy: 'Muhammad Hamza',
      approvalMethod: 'Phone Call',
      remarks: 'Customer authorized original screen replacement',
    },
    delivery: {},
    warranty: {
      duration: '90 Days',
      terms: '90 days touch & display guarantee. No warranty on physical cracks or water ingress.',
    },
    notes: 'Customer requested fast delivery before 6 PM today',
    createdAt: '2026-09-28 11:30:00',
    updatedAt: '2026-09-29 10:05:00',
  },
  {
    id: 'rep-2',
    repairNo: 'REP-2026-1002',
    date: '2026-09-27',
    time: '03:45 PM',
    customerId: 'pty-cus-2',
    customerName: 'Usman Ali',
    customerPhone: '+92 321 4567890',
    customerWhatsApp: '+92 321 4567890',
    customerCnic: '35201-1239874-5',
    customerAddress: 'Main Market, Gulberg II, Lahore',
    deviceType: 'Smartphone',
    brand: 'Samsung',
    model: 'Galaxy S23',
    imei1: '359871029481726',
    color: 'Phantom Black',
    storage: '128GB',
    devicePassword: 'Pattern: L-shape',
    physicalCondition: 'Minor scratches on back, screen clean with matte protector',
    checklist: {
      screen: 'Working',
      touch: 'Working',
      camera: 'Working',
      speaker: 'Working',
      microphone: 'Working',
      charging: 'Working',
      battery: 'Damaged',
      wifi: 'Working',
      bluetooth: 'Working',
      sim: 'Working',
      fingerprint: 'Working',
      faceId: 'Working',
      buttons: 'Working',
      vibration: 'Working',
      flash: 'Working',
      network: 'Working',
      body: 'Working',
      waterDamage: 'Working',
      backGlass: 'Working',
    },
    accessories: {
      charger: false,
      cable: false,
      box: false,
      sim: false,
      memoryCard: false,
      earphones: false,
      backCover: false,
    },
    photos: [],
    customerComplaint: 'Battery health degraded, dies suddenly at 25%, back cover heating while charging',
    problemDescription: 'Old battery puffed up slightly, internal resistance high',
    technicianDiagnosis: 'Swollen Li-Po battery pack. Replaced with original 5000mAh Samsung OEM pack.',
    faultFound: 'Faulty battery cells',
    requiredRepair: 'Battery replacement & thermal paste re-application',
    priority: 'Normal',
    status: 'Ready for Delivery',
    statusHistory: [
      {
        id: 'sh-11',
        status: 'Received',
        date: '2026-09-27',
        time: '03:45 PM',
        user: 'Waqas Ahmed',
        remarks: 'Phone received for battery change',
      },
      {
        id: 'sh-12',
        status: 'Approved',
        date: '2026-09-27',
        time: '04:00 PM',
        user: 'Waqas Ahmed',
        remarks: 'Approved at counter directly',
      },
      {
        id: 'sh-13',
        status: 'Under Repair',
        date: '2026-09-28',
        time: '11:00 AM',
        user: 'Bilal Hussain',
        technicianName: 'Bilal Hussain',
        remarks: 'Back panel opened, old battery removed safely',
      },
      {
        id: 'sh-14',
        status: 'Testing',
        date: '2026-09-28',
        time: '02:00 PM',
        user: 'Bilal Hussain',
        technicianName: 'Bilal Hussain',
        remarks: 'Fast charging & battery drainage test 100% passed',
      },
      {
        id: 'sh-15',
        status: 'Ready for Delivery',
        date: '2026-09-28',
        time: '05:00 PM',
        user: 'Bilal Hussain',
        remarks: 'Back sealed with waterproof adhesive. Ready for pickup.',
      }
    ],
    assignedTechnicianId: 'tech-2',
    assignedTechnicianName: 'Bilal Hussain',
    estimatedCompletionDate: '2026-09-28',
    completedDate: '2026-09-28',
    partsUsed: [
      {
        id: 'rpu-2',
        partItemId: 'part-2',
        partName: 'Samsung Galaxy S23 Original Battery 5000mAh',
        quantity: 1,
        costPrice: 4200,
        sellingPrice: 6500,
        totalSelling: 6500,
        addedAt: '2026-09-28 11:30 AM',
        addedBy: 'Bilal Hussain',
      }
    ],
    partsCost: 4200,
    partsSellingPrice: 6500,
    laborCharge: 1500,
    otherCharges: 0,
    discount: 0,
    totalCost: 5700,
    grandTotal: 8000,
    advancePayment: 3000,
    paidAmount: 3000,
    remainingAmount: 5000,
    paymentStatus: 'Partial',
    repairProfit: 2300,
    customerApproval: {
      status: 'Approved',
      date: '2026-09-27',
      time: '04:00 PM',
      approvedBy: 'Usman Ali',
      approvalMethod: 'In-Person',
    },
    delivery: {},
    warranty: {
      duration: '60 Days',
      terms: '60 days replacement warranty on battery performance & charging cycle stability',
    },
    createdAt: '2026-09-27 15:45:00',
    updatedAt: '2026-09-28 17:00:00',
  },
  {
    id: 'rep-3',
    repairNo: 'REP-2026-1003',
    date: '2026-09-29',
    time: '09:30 AM',
    customerName: 'Zainab Bibi',
    customerPhone: '+92 333 9988776',
    customerWhatsApp: '+92 333 9988776',
    customerAddress: 'DHA Phase 5, Lahore',
    deviceType: 'Smartphone',
    brand: 'Xiaomi',
    model: 'Redmi Note 12',
    imei1: '861029384756102',
    color: 'Ice Blue',
    storage: '128GB',
    devicePassword: 'None (Factory reset)',
    physicalCondition: 'Water dropped inside sink. Red moisture indicator triggered under SIM tray.',
    checklist: {
      screen: 'Not Tested',
      touch: 'Not Tested',
      camera: 'Not Tested',
      speaker: 'Not Tested',
      microphone: 'Not Tested',
      charging: 'Damaged',
      battery: 'Damaged',
      wifi: 'Not Tested',
      bluetooth: 'Not Tested',
      sim: 'Not Tested',
      fingerprint: 'Not Tested',
      faceId: 'Not Tested',
      buttons: 'Working',
      vibration: 'Not Tested',
      flash: 'Not Tested',
      network: 'Not Tested',
      body: 'Working',
      waterDamage: 'Damaged',
      backGlass: 'Working',
      other: 'Heavy corrosion around charging port & audio codec',
    },
    accessories: {
      charger: false,
      cable: false,
      box: false,
      sim: false,
      memoryCard: false,
      earphones: false,
      backCover: false,
    },
    photos: [],
    customerComplaint: 'Fell in water bucket yesterday. Does not turn on, red light blinks when plugged in.',
    problemDescription: 'Water ingress caused VDD_MAIN line short circuit to ground',
    technicianDiagnosis: 'Motherboard requires ultrasonic isopropyl bath, BGA power IC reballing, and new Type-C sub-board.',
    faultFound: 'Short circuit on charging rail & corroded flex connector',
    requiredRepair: 'IC level micro-soldering & sub-board replacement',
    priority: 'High',
    status: 'Waiting for Customer Approval',
    statusHistory: [
      {
        id: 'sh-21',
        status: 'Received',
        date: '2026-09-29',
        time: '09:30 AM',
        user: 'Malik Tariq',
        remarks: 'Received water damaged Redmi Note 12',
      },
      {
        id: 'sh-22',
        status: 'Diagnosis',
        date: '2026-09-29',
        time: '10:45 AM',
        user: 'Ustad Ali Raza',
        technicianName: 'Ustad Ali Raza',
        remarks: 'Motherboard opened & diagnosed under microscope',
      },
      {
        id: 'sh-23',
        status: 'Waiting for Customer Approval',
        date: '2026-09-29',
        time: '11:15 AM',
        user: 'Ustad Ali Raza',
        remarks: 'Estimate Rs 6,500 prepared. WhatsApp estimate dispatched to customer.',
      }
    ],
    assignedTechnicianId: 'tech-1',
    assignedTechnicianName: 'Ustad Ali Raza',
    estimatedCompletionDate: '2026-09-30',
    partsUsed: [
      {
        id: 'rpu-3',
        partItemId: 'part-3',
        partName: 'Type-C Fast Charging Flex Sub-Board',
        quantity: 1,
        costPrice: 700,
        sellingPrice: 2200,
        totalSelling: 2200,
        addedAt: '2026-09-29 11:10 AM',
        addedBy: 'Ustad Ali Raza',
      }
    ],
    partsCost: 700,
    partsSellingPrice: 2200,
    laborCharge: 4300,
    otherCharges: 0,
    discount: 0,
    totalCost: 5000,
    grandTotal: 6500,
    advancePayment: 1000,
    paidAmount: 1000,
    remainingAmount: 5500,
    paymentStatus: 'Partial',
    repairProfit: 1500,
    customerApproval: {
      status: 'Pending',
      remarks: 'WhatsApp estimate sent. Awaiting customer confirmation.',
    },
    delivery: {},
    warranty: {
      duration: '15 Days',
      terms: '15 days motherboard repair warranty. Water damage not covered if dropped again.',
    },
    createdAt: '2026-09-29 09:30:00',
    updatedAt: '2026-09-29 11:15:00',
  },
  {
    id: 'rep-4',
    repairNo: 'REP-2026-1004',
    date: '2026-09-25',
    time: '02:00 PM',
    customerName: 'Chaudhry Nadeem',
    customerPhone: '+92 302 4455667',
    customerWhatsApp: '+92 302 4455667',
    customerAddress: 'Johar Town G-Block, Lahore',
    deviceType: 'Smartphone',
    brand: 'Apple',
    model: 'iPhone 12',
    imei1: '358910293847561',
    color: 'Blue',
    storage: '64GB',
    physicalCondition: 'Good clean condition with slight scuffs on aluminum bezel',
    checklist: {
      screen: 'Working',
      touch: 'Working',
      camera: 'Working',
      speaker: 'Working',
      microphone: 'Working',
      charging: 'Damaged',
      battery: 'Working',
      wifi: 'Working',
      bluetooth: 'Working',
      sim: 'Working',
      fingerprint: 'Not Tested',
      faceId: 'Working',
      buttons: 'Working',
      vibration: 'Working',
      flash: 'Working',
      network: 'Working',
      body: 'Working',
      waterDamage: 'Working',
      backGlass: 'Working',
    },
    accessories: {
      charger: false,
      cable: false,
      box: false,
      sim: true,
      memoryCard: false,
      earphones: false,
      backCover: false,
    },
    photos: [],
    customerComplaint: 'Lightning cable falls out loosely. Only charges when tilted at a specific angle.',
    technicianDiagnosis: 'Charging port pins corroded & debris compacted inside jack',
    faultFound: 'Damaged lightning connector assembly',
    requiredRepair: 'Replaced genuine iPhone 12 charging port flex cable',
    priority: 'Normal',
    status: 'Delivered',
    statusHistory: [
      {
        id: 'sh-31',
        status: 'Received',
        date: '2026-09-25',
        time: '02:00 PM',
        user: 'Waqas Ahmed',
      },
      {
        id: 'sh-32',
        status: 'Under Repair',
        date: '2026-09-25',
        time: '03:30 PM',
        user: 'Bilal Hussain',
        technicianName: 'Bilal Hussain',
      },
      {
        id: 'sh-33',
        status: 'Ready for Delivery',
        date: '2026-09-25',
        time: '05:30 PM',
        user: 'Bilal Hussain',
      },
      {
        id: 'sh-34',
        status: 'Delivered',
        date: '2026-09-26',
        time: '11:00 AM',
        user: 'Malik Tariq',
        remarks: 'Delivered to customer. Paid full cash. Satisfied.',
      }
    ],
    assignedTechnicianId: 'tech-2',
    assignedTechnicianName: 'Bilal Hussain',
    estimatedCompletionDate: '2026-09-25',
    completedDate: '2026-09-25',
    partsUsed: [],
    partsCost: 1500,
    partsSellingPrice: 3500,
    laborCharge: 1500,
    otherCharges: 0,
    discount: 0,
    totalCost: 3000,
    grandTotal: 5000,
    advancePayment: 1000,
    paidAmount: 5000,
    remainingAmount: 0,
    paymentStatus: 'Paid',
    repairProfit: 2000,
    customerApproval: {
      status: 'Approved',
      date: '2026-09-25',
      time: '02:15 PM',
      approvedBy: 'Chaudhry Nadeem',
      approvalMethod: 'In-Person',
    },
    delivery: {
      deliveredDate: '2026-09-26',
      deliveredTime: '11:00 AM',
      deliveredBy: 'Malik Tariq',
      customerSignature: 'Ch. Nadeem (Verified in person)',
      customerRemarks: 'Fast service, charging perfectly now!',
    },
    warranty: {
      duration: '30 Days',
      startDate: '2026-09-26',
      expiryDate: '2026-10-26',
      terms: '30 days charging port warranty',
    },
    createdAt: '2026-09-25 14:00:00',
    updatedAt: '2026-09-26 11:00:00',
  }
];

// REPAIR PAYMENTS
export const initialRepairPayments: RepairPayment[] = [
  {
    id: 'rpay-1',
    repairId: 'rep-1',
    repairNo: 'REP-2026-1001',
    receiptNo: 'REC-REP-2026-101',
    date: '2026-09-28',
    time: '11:35 AM',
    customerName: 'Muhammad Hamza',
    amount: 10000,
    paymentMethod: 'JazzCash',
    type: 'Advance',
    receivedBy: 'Malik Tariq',
    notes: 'Advance token payment for OLED screen import',
    createdAt: '2026-09-28 11:35:00',
  },
  {
    id: 'rpay-2',
    repairId: 'rep-2',
    repairNo: 'REP-2026-1002',
    receiptNo: 'REC-REP-2026-102',
    date: '2026-09-27',
    time: '03:50 PM',
    customerName: 'Usman Ali',
    amount: 3000,
    paymentMethod: 'Cash',
    type: 'Advance',
    receivedBy: 'Waqas Ahmed',
    notes: 'Advance for battery order',
    createdAt: '2026-09-27 15:50:00',
  },
  {
    id: 'rpay-3',
    repairId: 'rep-3',
    repairNo: 'REP-2026-1003',
    receiptNo: 'REC-REP-2026-103',
    date: '2026-09-29',
    time: '09:35 AM',
    customerName: 'Zainab Bibi',
    amount: 1000,
    paymentMethod: 'Cash',
    type: 'Advance',
    receivedBy: 'Malik Tariq',
    notes: 'Initial checkup / advance token',
    createdAt: '2026-09-29 09:35:00',
  },
  {
    id: 'rpay-4',
    repairId: 'rep-4',
    repairNo: 'REP-2026-1004',
    receiptNo: 'REC-REP-2026-104',
    date: '2026-09-25',
    time: '02:05 PM',
    customerName: 'Chaudhry Nadeem',
    amount: 1000,
    paymentMethod: 'Cash',
    type: 'Advance',
    receivedBy: 'Waqas Ahmed',
    notes: 'Advance deposit',
    createdAt: '2026-09-25 14:05:00',
  },
  {
    id: 'rpay-5',
    repairId: 'rep-4',
    repairNo: 'REP-2026-1004',
    receiptNo: 'REC-REP-2026-105',
    date: '2026-09-26',
    time: '11:00 AM',
    customerName: 'Chaudhry Nadeem',
    amount: 4000,
    paymentMethod: 'Cash',
    type: 'Final / Delivery',
    receivedBy: 'Malik Tariq',
    notes: 'Final balance upon device delivery & testing',
    createdAt: '2026-09-26 11:00:00',
  }
];
